### ISSUE TITLE
Tutorial for starting out

### ISSUE THREAD

**Issue by verginer** [leerichardson/spew#4]
It would be really nice to have a kind of mini tutorial, maybe just a few lines to introduces the package.
I would love to use the library but it is difficult to extract from the man pages the steps that are involved in setting it up.

Nice project looking forward to using it 👍 .

**Comment by skgallagher** [comment]
Thank you for pointing this out!

We have a tutorial available here: http://stat.cmu.edu/~spew/use/.  We will make sure this is visible on the main page.

**Comment by verginer** [comment]
Nice, thanks looks really detailed, exactly what I was looking for.
