### ISSUE TITLE
SPEW.US Household, RT is always H, TYPE is always 1

### ISSUE THREAD

**Issue by JohnLevander** [leerichardson/spew#5]
In the SPEW.US data, the RT (Record Type) variable is always "H" which indicates a  "Housing Record."  The other value that RT can have is "Group Quarters Unit."  Additionally the TYPE variable in the Household file is always "1" which indicates a "Housing Unit."  The other values that TYPE can have are "Institutional group quarters" and "Noninstitutional group quarters."

If everyone in the SPEW.US synthetic ecosystem lives in a Housing Unit and there are 0 people that live in Group Quarters, one of the following must be true:

1. People that live in group quarters are represented in the synthetic population, but they are not represented as living in group quarters
2. People that live in group quarters are not represented in the synthetic population

Can you please clarify which of the above 2 options was used in the creation of the SPEW.US product?  Or did you use another option that I missed?

**Comment by leerichardson** [comment]
John,

We are doing #1. So we are matching the population totals for each tract (based on the marginal tables from ACS), but we are not including any group quarters

Thanks,
Lee
